[package]
name = "gui"
version = "0.1.0"
authors = ["Kiran Gopinathan <zcabkgo@ucl.ac.uk>"]

[[bin]]
name="gui"

[dependencies]
piston="0.37.0"
piston2d-graphics="0.26.0"
pistoncore-glutin_window="0.48.0"
piston2d-opengl_graphics="0.54.0"
